# Generated by Django 4.2.1 on 2023-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('选项一', models.CharField(max_length=200)), ('选项二', models.CharField(max_length=200)), ('选项三', models.CharField(max_length=200)), ('选项四', models.CharField(max_length=200))], max_length=200),
        ),
    ]
