# Generated by Django 4.2.1 on 2023-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', '选项A'), ('B', '选项B'), ('C', '选项C'), ('D', '选项D')], max_length=200),
        ),
    ]
